#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-KMsurv
Version  : 0.1.5
Release  : 3
URL      : https://cran.r-project.org/src/contrib/KMsurv_0.1-5.tar.gz
Source0  : https://cran.r-project.org/src/contrib/KMsurv_0.1-5.tar.gz
Summary  : Data sets from Klein and Moeschberger (1997), Survival Analysis
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
"Survival Analysis, Techniques for Censored and Truncated
        Data", Springer.

%prep
%setup -q -n KMsurv

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713891794

%install
export SOURCE_DATE_EPOCH=1713891794
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/KMsurv/DESCRIPTION
/usr/lib64/R/library/KMsurv/INDEX
/usr/lib64/R/library/KMsurv/Meta/Rd.rds
/usr/lib64/R/library/KMsurv/Meta/data.rds
/usr/lib64/R/library/KMsurv/Meta/features.rds
/usr/lib64/R/library/KMsurv/Meta/hsearch.rds
/usr/lib64/R/library/KMsurv/Meta/links.rds
/usr/lib64/R/library/KMsurv/Meta/nsInfo.rds
/usr/lib64/R/library/KMsurv/Meta/package.rds
/usr/lib64/R/library/KMsurv/NAMESPACE
/usr/lib64/R/library/KMsurv/R/KMsurv
/usr/lib64/R/library/KMsurv/R/KMsurv.rdb
/usr/lib64/R/library/KMsurv/R/KMsurv.rdx
/usr/lib64/R/library/KMsurv/data/aids.txt.gz
/usr/lib64/R/library/KMsurv/data/alloauto.txt.gz
/usr/lib64/R/library/KMsurv/data/allograft.txt.gz
/usr/lib64/R/library/KMsurv/data/azt.txt.gz
/usr/lib64/R/library/KMsurv/data/baboon.txt.gz
/usr/lib64/R/library/KMsurv/data/bcdeter.txt.gz
/usr/lib64/R/library/KMsurv/data/bfeed.txt.gz
/usr/lib64/R/library/KMsurv/data/bmt.txt.gz
/usr/lib64/R/library/KMsurv/data/bnct.txt.gz
/usr/lib64/R/library/KMsurv/data/btrial.txt.gz
/usr/lib64/R/library/KMsurv/data/burn.txt.gz
/usr/lib64/R/library/KMsurv/data/channing.txt.gz
/usr/lib64/R/library/KMsurv/data/drug6mp.txt.gz
/usr/lib64/R/library/KMsurv/data/drughiv.txt.gz
/usr/lib64/R/library/KMsurv/data/hodg.txt.gz
/usr/lib64/R/library/KMsurv/data/kidney.txt.gz
/usr/lib64/R/library/KMsurv/data/kidrecurr.txt.gz
/usr/lib64/R/library/KMsurv/data/kidtran.txt.gz
/usr/lib64/R/library/KMsurv/data/larynx.txt.gz
/usr/lib64/R/library/KMsurv/data/lung.txt.gz
/usr/lib64/R/library/KMsurv/data/pneumon.txt.gz
/usr/lib64/R/library/KMsurv/data/psych.txt.gz
/usr/lib64/R/library/KMsurv/data/rats.txt.gz
/usr/lib64/R/library/KMsurv/data/std.txt.gz
/usr/lib64/R/library/KMsurv/data/stddiag.txt.gz
/usr/lib64/R/library/KMsurv/data/tongue.txt.gz
/usr/lib64/R/library/KMsurv/data/twins.txt.gz
/usr/lib64/R/library/KMsurv/help/AnIndex
/usr/lib64/R/library/KMsurv/help/KMsurv.rdb
/usr/lib64/R/library/KMsurv/help/KMsurv.rdx
/usr/lib64/R/library/KMsurv/help/aliases.rds
/usr/lib64/R/library/KMsurv/help/paths.rds
/usr/lib64/R/library/KMsurv/html/00Index.html
/usr/lib64/R/library/KMsurv/html/R.css
